"""add practice sets and recommendations tables

Revision ID: 038ae11f1e8f
Revises: ac062c8628b6
Create Date: 2026-09-12 17:06:00.610978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038ae11f1e8f'
down_revision: Union[str, None] = 'ac062c8628b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='practice_set_status'), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=False),
    sa.Column('mastery_after', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sets_student_id'), 'practice_sets', ['student_id'], unique=False)
    op.create_index(op.f('ix_practice_sets_topic_id'), 'practice_sets', ['topic_id'], unique=False)
    op.create_table('practice_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_set_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'MULTI_SELECT', 'TRUE_FALSE', 'NUMERICAL', 'SHORT_ANSWER', 'LONG_ANSWER', name='practice_question_type'), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_questions_practice_set_id'), 'practice_questions', ['practice_set_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='recommendation_status'), nullable=False),
    sa.Column('practice_set_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_index(op.f('ix_recommendations_topic_id'), 'recommendations', ['topic_id'], unique=False)
    op.create_table('practice_question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_question_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_question_id'], ['practice_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_question_options_practice_question_id'), 'practice_question_options', ['practice_question_id'], unique=False)
    op.create_table('practice_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_set_id', sa.Uuid(), nullable=False),
    sa.Column('practice_question_id', sa.Uuid(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['practice_question_id'], ['practice_questions.id'], ),
    sa.ForeignKeyConstraint(['practice_set_id'], ['practice_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['practice_question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_set_id', 'practice_question_id', name='uq_practice_response_per_question')
    )
    op.create_index(op.f('ix_practice_responses_practice_question_id'), 'practice_responses', ['practice_question_id'], unique=False)
    op.create_index(op.f('ix_practice_responses_practice_set_id'), 'practice_responses', ['practice_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_responses_practice_set_id'), table_name='practice_responses')
    op.drop_index(op.f('ix_practice_responses_practice_question_id'), table_name='practice_responses')
    op.drop_table('practice_responses')
    op.drop_index(op.f('ix_practice_question_options_practice_question_id'), table_name='practice_question_options')
    op.drop_table('practice_question_options')
    op.drop_index(op.f('ix_recommendations_topic_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_practice_questions_practice_set_id'), table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_practice_sets_topic_id'), table_name='practice_sets')
    op.drop_index(op.f('ix_practice_sets_student_id'), table_name='practice_sets')
    op.drop_table('practice_sets')
    # ### end Alembic commands ###
