"""add parent portal tables

Revision ID: 06316e98fd73
Revises: 038ae11f1e8f
Create Date: 2026-09-13 15:33:19.768034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06316e98fd73'
down_revision: Union[str, None] = '038ae11f1e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_invite_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_invite_codes_code'), 'link_invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_link_invite_codes_student_id'), 'link_invite_codes', ['student_id'], unique=False)
    op.create_table('parent_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_profiles_user_id'), 'parent_profiles', ['user_id'], unique=True)
    op.create_table('parent_student_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='parent_link_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student_link')
    )
    op.create_index(op.f('ix_parent_student_links_parent_id'), 'parent_student_links', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    op.create_table('remarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('remark_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ACADEMIC', 'BEHAVIOR', 'ATTENDANCE', 'GENERAL', name='remark_category'), nullable=False),
    sa.Column('visible_to_parent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remarks_batch_id'), 'remarks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_remarks_student_id'), 'remarks', ['student_id'], unique=False)
    op.create_index(op.f('ix_remarks_teacher_id'), 'remarks', ['teacher_id'], unique=False)
    op.create_table('syllabus_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='syllabus_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('marked_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'subject_id', 'topic_id', name='uq_syllabus_progress_topic')
    )
    op.create_index(op.f('ix_syllabus_progress_batch_id'), 'syllabus_progress', ['batch_id'], unique=False)
    op.create_index(op.f('ix_syllabus_progress_subject_id'), 'syllabus_progress', ['subject_id'], unique=False)
    op.create_index(op.f('ix_syllabus_progress_topic_id'), 'syllabus_progress', ['topic_id'], unique=False)
    op.add_column('teacher_profiles', sa.Column('locality', sa.String(length=255), nullable=True))
    op.add_column('teacher_profiles', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('teacher_profiles', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_teacher_profiles_city'), 'teacher_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_teacher_profiles_locality'), 'teacher_profiles', ['locality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_profiles_locality'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_city'), table_name='teacher_profiles')
    op.drop_column('teacher_profiles', 'pincode')
    op.drop_column('teacher_profiles', 'city')
    op.drop_column('teacher_profiles', 'locality')
    op.drop_index(op.f('ix_syllabus_progress_topic_id'), table_name='syllabus_progress')
    op.drop_index(op.f('ix_syllabus_progress_subject_id'), table_name='syllabus_progress')
    op.drop_index(op.f('ix_syllabus_progress_batch_id'), table_name='syllabus_progress')
    op.drop_table('syllabus_progress')
    op.drop_index(op.f('ix_remarks_teacher_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_student_id'), table_name='remarks')
    op.drop_index(op.f('ix_remarks_batch_id'), table_name='remarks')
    op.drop_table('remarks')
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_id'), table_name='parent_student_links')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_parent_profiles_user_id'), table_name='parent_profiles')
    op.drop_table('parent_profiles')
    op.drop_index(op.f('ix_link_invite_codes_student_id'), table_name='link_invite_codes')
    op.drop_index(op.f('ix_link_invite_codes_code'), table_name='link_invite_codes')
    op.drop_table('link_invite_codes')
    # ### end Alembic commands ###
