"""add homework tables

Revision ID: 50b9bb1bd83c
Revises: f19e11a0e3a0
Create Date: 2026-09-08 14:52:27.391436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b9bb1bd83c'
down_revision: Union[str, None] = 'f19e11a0e3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('allow_late_submissions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_batch_id'), 'homework', ['batch_id'], unique=False)
    op.create_index(op.f('ix_homework_teacher_id'), 'homework', ['teacher_id'], unique=False)
    op.create_table('homework_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('homework_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_attachments_homework_id'), 'homework_attachments', ['homework_id'], unique=False)
    op.create_table('homework_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('homework_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'LATE', name='submission_status'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('homework_id', 'student_id', name='uq_submission_per_student')
    )
    op.create_index(op.f('ix_homework_submissions_homework_id'), 'homework_submissions', ['homework_id'], unique=False)
    op.create_index(op.f('ix_homework_submissions_student_id'), 'homework_submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_submissions_student_id'), table_name='homework_submissions')
    op.drop_index(op.f('ix_homework_submissions_homework_id'), table_name='homework_submissions')
    op.drop_table('homework_submissions')
    op.drop_index(op.f('ix_homework_attachments_homework_id'), table_name='homework_attachments')
    op.drop_table('homework_attachments')
    op.drop_index(op.f('ix_homework_teacher_id'), table_name='homework')
    op.drop_index(op.f('ix_homework_batch_id'), table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
