"""add assessment engine tables

Revision ID: 68ec7a248ed1
Revises: 50b9bb1bd83c
Create Date: 2026-09-08 15:21:05.436116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ec7a248ed1'
down_revision: Union[str, None] = '50b9bb1bd83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'PUBLISHED', 'CLOSED', name='assessment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_batch_id'), 'assessments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_assessments_teacher_id'), 'assessments', ['teacher_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'EXPIRED', name='attempt_status'), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_attempt_per_student')
    )
    op.create_index(op.f('ix_assessment_attempts_assessment_id'), 'assessment_attempts', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_attempts_student_id'), 'assessment_attempts', ['student_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'MULTI_SELECT', 'TRUE_FALSE', 'NUMERICAL', 'SHORT_ANSWER', 'LONG_ANSWER', name='question_type'), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_assessment_id'), 'questions', ['assessment_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('marked_for_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_response_per_question')
    )
    op.create_index(op.f('ix_responses_attempt_id'), 'responses', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_responses_question_id'), 'responses', ['question_id'], unique=False)
    op.create_table('response_selected_options',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['question_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', 'option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_selected_options')
    op.drop_index(op.f('ix_responses_question_id'), table_name='responses')
    op.drop_index(op.f('ix_responses_attempt_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_questions_assessment_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_assessment_attempts_student_id'), table_name='assessment_attempts')
    op.drop_index(op.f('ix_assessment_attempts_assessment_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index(op.f('ix_assessments_teacher_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_batch_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
