"""add analytics tables

Revision ID: 79a12d96eb03
Revises: 68ec7a248ed1
Create Date: 2026-09-08 15:50:09.834521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a12d96eb03'
down_revision: Union[str, None] = '68ec7a248ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendance_status'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'student_id', 'date', name='uq_attendance_per_day')
    )
    op.create_index(op.f('ix_attendance_batch_id'), 'attendance', ['batch_id'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('mastery_category', sa.String(length=30), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('recent_accuracy', sa.Float(), nullable=False),
    sa.Column('historical_accuracy', sa.Float(), nullable=False),
    sa.Column('difficulty_adjusted_accuracy', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('trend', sa.Enum('IMPROVING', 'DECLINING', 'STABLE', 'INSUFFICIENT_DATA', name='trend_direction'), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'topic_id', name='uq_snapshot_per_student_topic')
    )
    op.create_index(op.f('ix_performance_snapshots_student_id'), 'performance_snapshots', ['student_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_topic_id'), 'performance_snapshots', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_snapshots_topic_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_student_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_batch_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
